### ISSUE TITLE
VCS: New version, deprecated options

### ISSUE THREAD

**Issue by priyavadan** [Origen-SDK/origen_sim#15]
Documenting this here. with the latest VCS version, the -use_vpiobj option has been deprecated. We can now just specify the file name to include directly, no -use_vpiobj needed.

Example: 

Use
~~~
"#{WS}/../../../origen.c",
~~~

Instead of 
~~~
"-use_vpiobj #{WS}/../../../origen.c",
~~~

**Comment by ginty** [comment]
Fixed by - https://github.com/Origen-SDK/origen_sim/pull/25
