### ISSUE TITLE
Sim Delay discussion

### ISSUE THREAD

**Issue by priyavadan** [Origen-SDK/origen_sim#23]
@ginty based on our discussions from today. Is it possible to have the sim_delay method restore the pin  to the original state when the block is done? Currently we have to do the following in the code for stuff to work as expected:

~~~

        tester.sim_delay :erase_command do
          dut.pin(:done).assert!(1)
        end

        dut.pin(:done).dont_care!
~~~

Thanks!!

**Comment by ginty** [comment]
Fixed by #24
